kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "homebridge"
  namespace: {{ $.Values.namespace }}

spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: homebridge
                port: {{ .Values.service.port }}
