apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: homebridge
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
