# Default values for homebridge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: oznu/homebridge
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

autoscaling:
  enabled: false

serviceAccount:
  create: false

extraEnvs:
 - name: PUID
   value: "1000"
 - name: PGID
   value: "1000"
 - name: HOMEBRIDGE_CONFIG_UI
   value: "1"
 - name: HOMEBRIDGE_CONFIG_UI_PORT
   value: "8080"

podSecurityContext:
  fsGroup: 2000

securityContext:
    #capabilities:
    #cadrop:
    #ca- ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  allowPrivilegeEscalation: true
  #runAsUser: 1000

service:
  targetPort: 8080
  nodePort: 8090

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  #
